export const ADDING_BOOKS = 'ADDING_BOOKS';
export const ADD_BOOKS_SUCCESSFUL = 'ADD_BOOKS_SUCCESSFUL';
export const ADD_BOOKS_FAILED = 'ADD_BOOKS_FAILED';
export const AUTH_START = 'AUTH_START';
export const SIGNING_UP_SUCCESS = 'SIGNING_UP_SUCCESS';
export const SIGNING_UP_FAILED = 'SIGNING_UP_FAILED';